// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import NoteFormController from "./note_form_controller"
import TooltipController from "./tooltip_controller";
application.register("note-form", NoteFormController)
application.register("tooltip", TooltipController)